### PR TITLE
fix: use budgie-control center instead of gnome's

### PR DESCRIPTION
**Pull request by cat-master21**

### CODE REVIEW

**Comment by axtloss** [comment]
We're moving away from an onyx based on budgie and going with a custom gnome session with onyx, the budgie onyx is/shouldn't be distributed in the iso and the repos anymore.

**Comment by SomethingGeneric** [comment]
Given that we haven’t updated the repo with the gnome version yet, there’s no reason not to keep improving onyx in its current form. The new gnome version should also be on a new branch imho

**Comment by SomethingGeneric** [comment]
You’re forgetting the most important use case though, which is people who have onyx installed currently. **You** don’t have to work on the now-legacy version of onyx if you don’t want to, but there’s no reason that someone else can’t test this PR and merge it for the people still using the budgie-based version

**Comment by axtloss** [comment]
Right, didn't think about people already using onyx. I closed this pr because I was thinking that onyx isn't used at all anymore and is being deprecated.

**Comment by not-my-segfault** [comment]
I'm agreeing with @SomethingGeneric here, we should ensure compatibility with older systems still running budgie Onyx, I think we should merge this

**Review by not-my-segfault — APPROVED** [review]

**Comment by SomethingGeneric** [comment]
@not-my-segfault once we test it lol. Also, I think it’s good to ship both versions since they both have minor things that the other doesn’t

**Comment by SomethingGeneric** [comment]
@not-my-segfault my bad I meant we should probably also still depend on “gnome-control-center” too. And we’ll have to discuss the best approach to smoothly transition to the gnome version.

**Comment by not-my-segfault** [comment]
I'll move this to the org Discussions tab and merge this PR for now

**Pull request merged**
